# Generated by Django 6.0 on 2025-12-22 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('sensei_responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('taxa_inscricao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor_hex', models.CharField(max_length=7)),
                ('ordem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Judoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_nascimento', models.DateField()),
                ('registro_cbj', models.CharField(max_length=20, unique=True)),
                ('dojo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dojo')),
                ('faixa_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.faixa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
