# Generated by Django 6.0 on 2025-12-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atletas/')),
                ('destaque', models.BooleanField(default=False, help_text='Se marcado, aparece no carrossel principal.')),
                ('idade', models.IntegerField()),
                ('peso', models.CharField(help_text='Ex: 73kg', max_length=20)),
                ('categoria', models.CharField(help_text='Ex: Juvenil, Sênior', max_length=50)),
                ('graduacao', models.CharField(help_text='Ex: Faixa Preta 1º Dan', max_length=50)),
                ('principais_conquistas', models.TextField(help_text='Uma conquista por linha')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(help_text='Ex: Mestre Principal, Instrutor', max_length=100)),
                ('graduacao', models.CharField(help_text='Ex: Kodansha 6º Dan', max_length=100)),
                ('foto', models.ImageField(upload_to='senseis/')),
                ('biografia', models.TextField()),
                ('anos_experiencia', models.IntegerField(default=0)),
                ('especialidades', models.CharField(help_text='Separe por vírgula. Ex: Kata, Newaza', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='judoca',
            name='dojo',
        ),
        migrations.RemoveField(
            model_name='judoca',
            name='faixa_atual',
        ),
        migrations.RemoveField(
            model_name='judoca',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data']},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='taxa_inscricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_fim',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(default='8:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_info',
            field=models.URLField(blank=True, help_text="Link para 'Saiba mais'", null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('competicao', 'Competição'), ('seminario', 'Seminário'), ('interno', 'Interno')], default='competicao', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Dojo',
        ),
        migrations.DeleteModel(
            name='Faixa',
        ),
        migrations.DeleteModel(
            name='Judoca',
        ),
    ]
