# Generated by Django 5.2.9 on 2025-12-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_atleta_contato_sensei_remove_judoca_dojo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atleta",
            name="idade",
        ),
        migrations.AddField(
            model_name="atleta",
            name="data_nascimento",
            field=models.DateField(
                default="2000-01-01", verbose_name="Data de Nascimento"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="atleta",
            name="principais_conquistas",
            field=models.TextField(
                blank=True, help_text="Uma conquista por linha", null=True
            ),
        ),
    ]
